# Generated by Django 5.0.2 on 2024-02-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='keyword_mouse',
        ),
    ]
